# Assignment_1_NumPy

### Q1: Import numpy as np

In [1]:
import numpy as np

### Q2: How to create a 1D array?

In [4]:
arr = np.arange(10)

In [7]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Q3: How to create a 2D array?

In [13]:
arr2 = np.arange(12).reshape(4,3)

In [14]:
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### Q4: How to create a 3D array?

In [15]:
arr3 = np.arange(24).reshape(2,3,4)

In [16]:
arr3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [36]:
from IPython.display import Image, display
from IPython.core.display import HTML 
#display(Image(url= "https://i.postimg.cc/fRFKP3bZ/pic.png"))
Image(url= "https://i.postimg.cc/fRFKP3bZ/pic.png", width=400, height=400)

### Q4: How to reshape an array?

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr = np.arange(10)
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Q5: Replace all odd numbers in arr with -1?

In [44]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### Q6: Convert a 1D array to a 2D array with 2 rows?

In [48]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr = np.arange(10)
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Q8: How to stack two arrays vertically?

In [59]:
a = np.arange(10).reshape(2, -1)
b = np.arange(10).reshape(2, -1)
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [60]:
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Q9. How to generate custom sequences in numpy without hardcoding?

In [62]:
a = np.array([1,2,3])

In [63]:
np.r_[np.repeat(a,3), np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

### Q10: How to get the common items between two python numpy arrays?

In [64]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

### Q11: How to remove from one array those items that exist in another?

In [66]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [67]:
# From "a" remove all of "b"
np.setdiff1d(a,b)

array([1, 2, 3, 4])

### Q12: How to get the positions where elements of two arrays match?

In [68]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [69]:
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

### Q13: How to extract all numbers between a given range from a numpy array?

In [77]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [78]:
a = np.arange(15)

In [79]:
index = np.where((a >= 5) & (a <= 10))

In [80]:
a[index]

array([ 5,  6,  7,  8,  9, 10])

### Q14: How to swap two columns in a 2d numpy array?

In [84]:
# Swap columns 1 and 2 in the array arr.
#arr = np.arange(9).reshape(3,3)
#arr
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

### Q15: How to swap two rows in a 2d numpy array?

In [85]:
# Swap rows 1 and 2 in the array arr
#arr = np.arange(9).reshape(3,3)
#arr
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

### Q16: How to reverse the rows of a 2D array?

In [87]:
# Reverse the rows of a 2D array arr
# Input
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

### Q17: How to reverse the columns of a 2D array?

In [88]:
# Reverse the columns of a 2D array arr
# Input
arr = np.arange(9).reshape(3,3)

arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

### Q18: How to create a 2D array containing random floats between 5 and 10?

In [90]:
# Input
arr = np.arange(9).reshape(3,3)
rand_arr = np.random.uniform(5,10, size=(5,3))
rand_arr

array([[7.27533005, 7.53072505, 6.58246457],
       [5.48011244, 5.47247117, 9.0374999 ],
       [6.15614601, 7.51095032, 8.80675968],
       [8.40533583, 9.79187312, 7.81181357],
       [6.34035164, 7.14410405, 5.99449308]])

### Q19: How to print only 3 decimal places in python numpy array?

In [91]:
# Input
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr[:4]

array([[0.432, 0.812, 0.982],
       [0.062, 0.125, 0.312],
       [0.156, 0.049, 0.579],
       [0.021, 0.191, 0.556]])

### Q20: How to check Array dimension?

In [93]:
a = np.arange(15).reshape(3,5)

In [94]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [95]:
a.ndim

2

### Q21: How to check Array dimension types?

In [96]:
a.dtype

dtype('int32')

### Q22: How to check Array dimension size?

In [100]:
a.itemsize

4

### Q23: How to check Array dimension memoryview?

In [104]:
a.data

### Q24: How to create Zero Array?

In [105]:
n=np.zeros((5,5))
n

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Q25: How to create One's Array?

In [106]:
n=np.ones((7,7))
n

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

### Q26: How to create One's Array?

In [107]:
a=np.empty((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Q27: Create sequences of numbers

In [108]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [109]:
np.arange(50,200,10)

array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140, 150, 160, 170,
       180, 190])

### Q28: Vetorized Operation

In [110]:
a=np.random.randn((10))
a

array([ 1.328,  0.294, -1.089, -0.7  ,  1.328,  1.404, -0.905, -0.065,
        0.459, -0.736])

### Q29: Random

In [111]:
a=np.random.randn((10))
a

array([ 1.108, -0.71 , -0.127,  0.222, -0.891, -1.155, -0.134,  0.355,
       -1.601,  1.39 ])

In [112]:
x=np.random.randn((10))
x

array([-0.771,  1.228,  0.396, -0.76 , -0.79 , -1.432, -0.174,  0.682,
       -1.376, -1.006])

### Q30: How to add Array's

In [113]:
a+x

array([ 0.336,  0.517,  0.269, -0.538, -1.681, -2.587, -0.307,  1.038,
       -2.977,  0.384])

### Q31: How to numpy multiply arrays

In [115]:
a*x

array([-0.854, -0.872, -0.05 , -0.168,  0.704,  1.654,  0.023,  0.242,
        2.203, -1.398])

### Q32: How to divide in Numpy

In [116]:
a%b

array([1.108, 1.29 , 9.873, 0.222, 6.109, 2.845, 8.866, 0.355, 7.399,
       1.39 ])

### Q33: How to create Boolean Array

In [118]:
z= np.array([4, 4, 4, 4, 4, 4])
print(z == 4)

[ True  True  True  True  True  True]


In [119]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr=arr1==arr2
arr

array([[False, False, False],
       [False, False, False]])

### Q34: Index Slicing

In [122]:
d=np.array([1,2,4,6,8,9,10,17])
d[4]

8

In [123]:
d[d<6]

array([1, 2, 4])

In [124]:
d[[3,5]]

array([6, 9])

### Q35: non-negative square-root of an array

In [125]:
a=np.array([2,4,6,9,7,10])

In [126]:
np.sqrt(a)

array([1.414, 2.   , 2.449, 3.   , 2.646, 3.162])

### Q36: First array elements raised to powers from second array

In [127]:
c=np.array([12,24,56,47,31])

In [128]:
np.power(c,2)

array([ 144,  576, 3136, 2209,  961], dtype=int32)

### Q37: Reverse a Vector

In [129]:
a=np.array([1,3,6,4,7])
print(a)
print(a[-1::-1])

[1 3 6 4 7]
[7 4 6 3 1]


### Q38: Linear algebra

In [130]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
a

array([[1., 2.],
       [3., 4.]])

In [131]:
b = np.array([[2,5], [4,6]])
b

array([[2, 5],
       [4, 6]])

### Q39: along diagonals of the array

In [132]:
a.trace()

5.0

### Q40: Matrix transpose

In [133]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

### Q41: Compute the (multiplicative) inverse of a matrix

In [134]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### Q42: Sum of the Array

In [135]:
a.sum()

10.0

### Q43: Dot product of two arrays

In [136]:
a.dot(b)

array([[10., 17.],
       [22., 39.]])

In [137]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

### Q44:  product of array elements over a given axis

In [138]:
x = np.array([536870910, 536870910, 536870910, 536870910])
np.prod(x)

16

### Q45: Changing the shape of an array

In [142]:
x.ravel()

array([536870910, 536870910, 536870910, 536870910])

### Q46: Copies and Views

In [144]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

In [145]:
b = a

In [146]:
b is a

True

### Q47: View or Shallow Copy

In [147]:
c = a.view()

In [148]:
c is a

False

### Q48: Deep Copy

In [149]:
d = a.copy()

In [150]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [151]:
d is a

False

### Q49: Where in Numpy

In [154]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b,a,b)

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

### Q50: Numpy time required

In [155]:
[i for i in range(100000000)][:20000000]
%time

Wall time: 0 ns
